language: node_js
sudo: false
node_js:
  - "5.11"
cache:
  apt: true
  directories:
    - node_modules
addons:
  ssh_known_hosts: git.coding.net
script:
  - hexo clean && hexo generate
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_5eaf022bdb7b_key -iv $encrypted_5eaf022bdb7b_iv -in ./.travis/coding.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - cp ./.travis/ssh_config ~/.ssh/config
  - chmod 600 ~/.ssh/config
  - git config --global user.name "laizw"
  - git config --global user.email i@laizw.cn
deploy:
  provider: script
  script: hexo deploy
  skip_cleanup: true
  on:
    branch: master